In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [4]:
arr1 = np.array([[10,20,30],[40,50,60]])
print(arr1)

[[10 20 30]
 [40 50 60]]


In [5]:
arr2 = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr2)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


In [1]:
a = "Hello World"
print(a, type(a))

Hello World <class 'str'>


In [8]:
import numpy as np
arr3 = np.array([20, 30, "hello", 40, "ram", 50, 60])
print(arr3[0:3])
print(arr3[1:3:2])
print(arr3[1:3])
print(arr3[:2])
print(arr3[2:])

['20' '30' 'hello']
['30']
['30' 'hello']
['20' '30']
['hello' '40' 'ram' '50' '60']


In [23]:
arr4 = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(arr4[:2])
print(arr4[:2, 0:2])
print(arr4[:2, 1:2])

[[10 20 30 40]
 [50 60 70 80]]
[[10 20]
 [50 60]]
[[20]
 [60]]
