In [6]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
arr1 = np.array([[10,20,30],[40,50,60]])
print(arr1)

[[10 20 30]
 [40 50 60]]


In [7]:
arr2 = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr2)



NameError: name 'np' is not defined